name = "PanchoRing"
author = "CapNapu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3538075bcda4c61f3ca7aa2c5095950ab66302381382b4ea7a5035919d1afd5"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
