name = "PanchoRing"
author = "CapNapu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4a0c266dfa9b49f8222b8a445cfd06ce0ccf3f6ed8c8e15acd8a586910e824c"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
